### ISSUE TITLE
颜色冲突

### ISSUE THREAD

**Issue by yuxixi0613** [imseanpan/Macaroon-Theme#3]
在vscode的源代码管理中，修改文件中的删除的某行的颜色和某些属性颜色冲突，导致看不清，麻烦修整一下，

![image](https://user-images.githubusercontent.com/84132393/219314313-a65326f4-0824-452c-aa08-22c9bc73a0c1.png)

你的主题虽然用户量少，但是个人最喜欢。望采纳。

**Comment by imseanpan** [comment]
稍后我看下,最近一直在忙项目,这个皮肤其实是有升级的.没弄上来....-.-
稍等我忙过这段时间

________________________________
发件人: 鱼嘻嘻 ***@***.***>
发送时间: 2023年2月16日 16:46
收件人: imseanpan/Macaroon-Theme ***@***.***>
抄送: Subscribed ***@***.***>
主题: [imseanpan/Macaroon-Theme] 颜色冲突 (Issue #3)


在vscode的源代码管理中，修改文件中的删除的某行的颜色和某些属性颜色冲突，导致看不清，麻烦修整一下，

[image]<https://user-images.githubusercontent.com/84132393/219313775-6d1382a0-a60a-48a3-b021-124b999d5d4f.png>

你的主题虽然用户量少，但是个人最喜欢。望采纳。

―

**Comment by imseanpan** [comment]
更新发布15版本,可以看看是否ok?

**Comment by yuxixi0613** [comment]
> 更新发布15版本,可以看看是否ok?
比之前好一些了，感谢！
![image](https://user-images.githubusercontent.com/84132393/219962186-d6b24b38-269e-4854-89a5-f0ad6708a2df.png)
